jobname=yolo_hyperparameter_tuning

OSDF_LOCATION=osdf:///ospool/ap41/data/rei.jones
HOME_LOCATION=/home/rei.jones/code/yolo26

NewProcess=$(Process)

executable = yolo_hyperparameter_executable.sh
arguments = $(NewProcess)

# Log, error, and output file locations

log = logs/$(jobname)/jobid$(NewProcess)/$(Cluster)_$(NewProcess).log
error = logs/$(jobname)/jobid$(NewProcess)/$(Cluster)_$(NewProcess).err
output = logs/$(jobname)/jobid$(NewProcess)/$(Cluster)_$(NewProcess).out

# Transfer input files

transfer_input_files = $(HOME_LOCATION)/scripts/yolo_tune_full.py, $(OSDF_LOCATION)/data/events_45_135_tune/images/imgtrain.tar.gz, $(OSDF_LOCATION)/data/events_45_135_tune/images/imgval.tar.gz, $(OSDF_LOCATION)/data/events_45_135_tune/labels/labeltrain.tar.gz, $(OSDF_LOCATION)/data/events_45_135_tune/labels/labelval.tar.gz, $(HOME_LOCATION)/config/data.yaml

# Transfer output files

transfer_output_remaps = "results.tar = $(OSDF_LOCATION)/job/$(jobname)/$(jobname)_$(Cluster)_$(NewProcess).tar"

+JobDurationCategory = "Long"

container_image = osdf:///ospool/ap41/data/rei.jones/containers/yolo_container.sif


# Tell HTCondor requirements (e.g., operating system) your job needs,
# what amount of compute resources each job will need on the computer where it runs.
request_gpus = 1
request_cpus = 3
request_memory = 64GB
request_disk = 7GB

# Tell HTCondor the number of instances to run:
queue 1
