jobname=nudobe

PRESSURE=1bar

event_type=events_full_range

OSDF_LOCATION=/ospool/ap41/data/rei.jones
HOME_LOCATION=/home/rei.jones/code/NEXT_nudobe/

NewProcess=$(Process)

executable = SimulateEvents.sh
arguments = $(NewProcess) $(jobname) $(EVENT_TYPE) $(PRESSURE)

# Log, error, and output file locations

log = logs/$(EVENT_TYPE)/$(PRESSURE)bar/jobid$(NewProcess)/$(Cluster)_$(NewProcess).log
error = logs/$(EVENT_TYPE)/$(PRESSURE)bar/jobid$(NewProcess)/$(Cluster)_$(NewProcess).err
output = logs/$(EVENT_TYPE)/$(PRESSURE)bar/jobid$(NewProcess)/$(Cluster)_$(NewProcess).out

# Transfer input files

transfer_input_files = $(HOME_LOCATION)/config/$(INIT),$(HOME_LOCATION)/config/$(CONFIG),$(HOME_LOCATION)/files/$(EVENT_TYPE).txt,$(HOME_LOCATION)/scripts/SmearEvents.py,$(HOME_LOCATION)/scripts/CompressEvents.py, $(HOME_LOCATION)/scripts/setup_cluster.sh, $(HOME_LOCATION)/scripts/ProjectPlotsNew.py

# Transfer output files

transfer_output_remaps = "nudobe.tar = $(OSDF_LOCATION)/job/$(jobname)/$(EVENT_TYPE)/$(PRESSURE)bar/$(EVENT_TYPE)_$(PRESSURE)bar_$(Cluster)_$(NewProcess).tar"

+JobDurationCategory = "Medium"

container_image = osdf:///ospool/ap41/data/rei.jones/containers/rei_nexus.sif

# Tell HTCondor requirements (e.g., operating system) your job needs,
# what amount of compute resources each job will need on the computer where it runs.
requirements = (Arch == "X86_64" && TARGET.GLIDEIN_ResourceName =!= "Lehigh - Hawk" && TARGET.GLIDEIN_ResourceName =!= "UA-LR-ITS-EP")
request_cpus = 1
request_memory = 5GB
request_disk = 5GB

# If submitting more than 10k jobs use this statement
# max_idle = 2000

# Tell HTCondor the number of instances to run:
queue 1
[rei.jones@ap41 NEXT_nudobe]$ vim SimulateEvents.sub
[rei.jones@ap41 NEXT_nudobe]$ cat SimulateEvents.sub
jobname=nudobe

PRESSURE=1

EVENT_TYPE=events_full_range

INIT = custom.init.mac
CONFIG = custom.config.mac

OSDF_LOCATION=/ospool/ap41/data/rei.jones
HOME_LOCATION=/home/rei.jones/code/NEXT_nudobe/

NewProcess=$(Process)

executable = SimulateEvents.sh
arguments = $(NewProcess) $(jobname) $(EVENT_TYPE) $(PRESSURE)

# Log, error, and output file locations

log = logs/$(EVENT_TYPE)/$(PRESSURE)bar/jobid$(NewProcess)/$(Cluster)_$(NewProcess).log
error = logs/$(EVENT_TYPE)/$(PRESSURE)bar/jobid$(NewProcess)/$(Cluster)_$(NewProcess).err
output = logs/$(EVENT_TYPE)/$(PRESSURE)bar/jobid$(NewProcess)/$(Cluster)_$(NewProcess).out

# Transfer input files

transfer_input_files = $(HOME_LOCATION)/config/$(INIT),$(HOME_LOCATION)/config/$(CONFIG),$(HOME_LOCATION)/files/$(EVENT_TYPE).txt,$(HOME_LOCATION)/scripts/SmearEvents.py,$(HOME_LOCATION)/scripts/CompressEvents.py, $(HOME_LOCATION)/scripts/setup_cluster.sh, $(HOME_LOCATION)/scripts/ProjectPlotsNew.py

# Transfer output files

transfer_output_remaps = "nudobe.tar = $(OSDF_LOCATION)/job/$(jobname)/$(EVENT_TYPE)/$(PRESSURE)bar/$(EVENT_TYPE)_$(PRESSURE)bar_$(Cluster)_$(NewProcess).tar"

+JobDurationCategory = "Medium"

container_image = osdf:///ospool/ap41/data/rei.jones/containers/rei_nexus.sif

# Tell HTCondor requirements (e.g., operating system) your job needs,
# what amount of compute resources each job will need on the computer where it runs.
requirements = (Arch == "X86_64" && TARGET.GLIDEIN_ResourceName =!= "Lehigh - Hawk" && TARGET.GLIDEIN_ResourceName =!= "UA-LR-ITS-EP")
request_cpus = 1
request_memory = 5GB
request_disk = 5GB

# If submitting more than 10k jobs use this statement
# max_idle = 2000

# Tell HTCondor the number of instances to run:
queue 1